namespace Waffle.DeltaruneSaveApi;

public enum Armor
{
    None = 0,
    AmberCard = 1,
    DiceBrace = 2,
    PinkRibbon = 3,
    WhiteRibbon = 4,
    IronShackle = 5,
    MouseToken = 6,
    Jevilstail = 7,
    SilverCard = 8,
    TwinRibbon = 9,
    GlowWrist = 10,
    ChainMail = 11,
    BShotBowtie = 12,
    SpikeBand = 13,
    SilverWatch = 14,
    TensionBow = 15,
    Mannequin = 16,
    DarkGoldBand = 17,
    SkyMantle = 18,
    SpikeShackle = 19,
    FrayedBowtie = 20,
    Dealmaker = 21,
    RoyalPin = 22,
    ShadowMantle = 23,
    LodeStone = 24,
    GingerGuard = 25,
    BlueRibbon = 26,
    TennaTie = 27,
    Waferguard = 50,
    MysticBand = 51,
    PowerBand = 52,
    PrincessRbn = 53,
    GoldWidow = 54,
}